[project]
name = "btok"
version = "0.3.1"
authors = [
    { name="Hansimov" },
]
description = "A Python tokenizer trained on modern web corpus"
readme = "README.md"
license = "MIT"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = ["tclogger", "sentencepiece"]

[project.urls]
Homepage = "https://github.com/Hansimov/btok"
Issues = "https://github.com/Hansimov/btok/issues"
